default_context:
  project_name: 'wds'
  project_slug: 'wds'
  domain_main: 'wds.com'
  domain_staging: 'stag.wds.com'
  docker_swarm_stack_name_main: 'wds-com'
  docker_swarm_stack_name_staging: 'stag-wds-com'
  secret_key: 'ea1324135665c45c45d705276de252e4b35bcf8bdaa18508f97a402ed9ee2d24'
  first_superuser: 'admin@wds.com'
  first_superuser_password: '6239c6877e6bd88e496c67cc007727c80c5d33905858c06c786af20f98a253b1'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.wds.com", "https://stag.wds.com", "https://wds.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@wds.com'
  postgres_password: 'ca1e731ee9b652150b498df10391c82969003a8b283caa7b91c2061d790bb014'
  pgadmin_default_user: 'admin@wds.com'
  pgadmin_default_user_password: '4a39fc95569012359bec3ead8fcf088c684a3715ca5b7818b6a5cce9e5e7057c'
  traefik_constraint_tag: 'wds.com'
  traefik_constraint_tag_staging: 'stag.wds.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:6239c6877e6bd88e496c67cc007727c80c5d33905858c06c786af20f98a253b1'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
