version: "3.3"
services:

  db:
    image: postgres:12
    env_file:
      - .env
  
  api:
    container_name: fastapi
    depends_on:
      - db
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - '8000:8000'
    build:
      context: ./backend
      dockerfile: Dockerfile
