version: "3.4"

volumes:
    pg_data:


services:

  db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5543:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
    container_name: fastapi
    depends_on:
      - db
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - '8000:8000'
    build:
      context: ./backend
      dockerfile: Dockerfile
