"""First revision

Revision ID: d4867f3a4c0a
Revises:
Create Date: 2019-04-17 13:53:32.978401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4867f3a4c0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("wds_serial", sa.String(), nullable=False),
        sa.Column("func_status", sa.String(), nullable=True),
        sa.Column("accum_sys_time", sa.Integer(), nullable=True),
        sa.Column("accum_standby", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True)),
        sa.Column("last_updated", sa.DateTime(timezone=True)),
        sa.PrimaryKeyConstraint("wds_serial"),
    )
    op.create_index(op.f("ix_func_status"), "item", ["func_status"], unique=False)
    op.create_index(op.f("ix_wds_serial"), "item", ["wds_serial"], unique=True)
    op.create_index(op.f("ix_time_updated"), "item", ["last_updated"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_title"), table_name="item")
    op.drop_index(op.f("ix_item_id"), table_name="item")
    op.drop_index(op.f("ix_item_description"), table_name="item")
    op.drop_table("item")
    # ### end Alembic commands ###
